import os

ORACLE_USER = 'SYSTEM'
ORACLE_PASSWORD = '1234'
ORACLE_HOST = 'localhost'
ORACLE_PORT = '1521'
ORACLE_SERVICE = 'FREEPDB1'

SQLACHEMY_DATEBASE_URL = f'oracle+oracledb://{ORACLE_USER}:{ORACLE_PASSWORD}@{ORACLE_HOST}:{ORACLE_PORT}/?sevice_name={ORACLE_SERVICE}'
SQLACHEMY_TRACK_MODIFICATIONS = False